openapi: "3.0.0"
info:
  description: "This is a sample server Foo server."
  version: "1.0.0"
  title: "Foo!"


paths:
  /pet:
    post:
      summary: "Add a new Foo!"
      operationId: "add_foo"
      requestBody:
        description: "This is what your new Foo looks like!"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Foo'
      responses:
        '200':
          description: "Status about your new Foo"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
  /foo/{foo_id}:
    get:
      description: "Lookup an old Foo!"
      operationId: "get_foo_by_id"
      parameters:
        - name: "foo_id"
          in: "path"
          description: "ID of Foo to return"
          required: true
          schema:
            type: number
      responses:
        '200':
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Foo"
        '400':
          description: "Invalid ID supplied"
        '404':
          description: "Foo not found"

components:
  schemas:
    Foo:
      type: "object"
      required:
      - "name"
      properties:
        id:
          type: "integer"
          format: "int64"
        name:
          type: "string"
          example: "An example Foo!"
    ApiResponse:
      type: "object"
      properties:
        code:
          type: "integer"
          format: "int32"
        type:
          type: "string"
        message:
          type: "string"

