version: '3'
services:
  foo_app:
    image: microservicefromscratch:1.0
    ports:
      - 5501:5501

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=foo